### ISSUE TITLE
ursus command creating a json file

### ISSUE THREAD

**Issue by Lamiiine** [All-About-Berlin/ursus#3]
I followed the steps and created this folder structure
my-website/ <- You are here
├─ content/
│  └─ posts/
│     └─ first-post.md
└─ templates/
   └─ posts/
      └─ entry.html.jinja
but when I run ursus, it creates an output folder with an index json file inside it and not as mentioned in the doc ./output/posts/first-post.html

**Comment by nicbou** [comment]
Please provide more information. What command did you type? From which directory? What was the log output?

Without any information, I cannot assist you

**Comment by nicbou** [comment]
Closed until more information is provided
